name: Page Performance Tracking Automation

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  check-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run performance tracker
        run: python fetch_psi.py
